name: gaml_cce
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  colorize: ^3.0.0
  meta: ^1.7.0